//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace April2021Client.SR {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vlasnik", Namespace="http://schemas.datacontract.org/2004/07/April2021", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Vlasnik : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JMBGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrezimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<April2021Client.SR.Vozilo> VozilaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JMBG {
            get {
                return this.JMBGField;
            }
            set {
                if ((object.ReferenceEquals(this.JMBGField, value) != true)) {
                    this.JMBGField = value;
                    this.RaisePropertyChanged("JMBG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime {
            get {
                return this.PrezimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true)) {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<April2021Client.SR.Vozilo> Vozila {
            get {
                return this.VozilaField;
            }
            set {
                if ((object.ReferenceEquals(this.VozilaField, value) != true)) {
                    this.VozilaField = value;
                    this.RaisePropertyChanged("Vozila");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vozilo", Namespace="http://schemas.datacontract.org/2004/07/April2021", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Vozilo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BojaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private April2021Client.SR.Vlasnik VlasnikField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Boja {
            get {
                return this.BojaField;
            }
            set {
                if ((object.ReferenceEquals(this.BojaField, value) != true)) {
                    this.BojaField = value;
                    this.RaisePropertyChanged("Boja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marka {
            get {
                return this.MarkaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkaField, value) != true)) {
                    this.MarkaField = value;
                    this.RaisePropertyChanged("Marka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public April2021Client.SR.Vlasnik Vlasnik {
            get {
                return this.VlasnikField;
            }
            set {
                if ((object.ReferenceEquals(this.VlasnikField, value) != true)) {
                    this.VlasnikField = value;
                    this.RaisePropertyChanged("Vlasnik");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR.IRegistracijaVozila")]
    public interface IRegistracijaVozila {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozila/Registracija", ReplyAction="http://tempuri.org/IRegistracijaVozila/RegistracijaResponse")]
        void Registracija(April2021Client.SR.Vlasnik vl, April2021Client.SR.Vozilo voz);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozila/Registracija", ReplyAction="http://tempuri.org/IRegistracijaVozila/RegistracijaResponse")]
        System.Threading.Tasks.Task RegistracijaAsync(April2021Client.SR.Vlasnik vl, April2021Client.SR.Vozilo voz);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozila/VratiVozila", ReplyAction="http://tempuri.org/IRegistracijaVozila/VratiVozilaResponse")]
        System.Collections.Generic.List<April2021Client.SR.Vozilo> VratiVozila(string jmbg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozila/VratiVozila", ReplyAction="http://tempuri.org/IRegistracijaVozila/VratiVozilaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<April2021Client.SR.Vozilo>> VratiVozilaAsync(string jmbg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozila/VratiVlasnikeModela", ReplyAction="http://tempuri.org/IRegistracijaVozila/VratiVlasnikeModelaResponse")]
        System.Collections.Generic.List<April2021Client.SR.Vlasnik> VratiVlasnikeModela(string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozila/VratiVlasnikeModela", ReplyAction="http://tempuri.org/IRegistracijaVozila/VratiVlasnikeModelaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<April2021Client.SR.Vlasnik>> VratiVlasnikeModelaAsync(string model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozila/VratiSvaVozila", ReplyAction="http://tempuri.org/IRegistracijaVozila/VratiSvaVozilaResponse")]
        System.Collections.Generic.List<April2021Client.SR.Vozilo> VratiSvaVozila();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegistracijaVozila/VratiSvaVozila", ReplyAction="http://tempuri.org/IRegistracijaVozila/VratiSvaVozilaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<April2021Client.SR.Vozilo>> VratiSvaVozilaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegistracijaVozilaChannel : April2021Client.SR.IRegistracijaVozila, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistracijaVozilaClient : System.ServiceModel.ClientBase<April2021Client.SR.IRegistracijaVozila>, April2021Client.SR.IRegistracijaVozila {
        
        public RegistracijaVozilaClient() {
        }
        
        public RegistracijaVozilaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistracijaVozilaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistracijaVozilaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistracijaVozilaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Registracija(April2021Client.SR.Vlasnik vl, April2021Client.SR.Vozilo voz) {
            base.Channel.Registracija(vl, voz);
        }
        
        public System.Threading.Tasks.Task RegistracijaAsync(April2021Client.SR.Vlasnik vl, April2021Client.SR.Vozilo voz) {
            return base.Channel.RegistracijaAsync(vl, voz);
        }
        
        public System.Collections.Generic.List<April2021Client.SR.Vozilo> VratiVozila(string jmbg) {
            return base.Channel.VratiVozila(jmbg);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<April2021Client.SR.Vozilo>> VratiVozilaAsync(string jmbg) {
            return base.Channel.VratiVozilaAsync(jmbg);
        }
        
        public System.Collections.Generic.List<April2021Client.SR.Vlasnik> VratiVlasnikeModela(string model) {
            return base.Channel.VratiVlasnikeModela(model);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<April2021Client.SR.Vlasnik>> VratiVlasnikeModelaAsync(string model) {
            return base.Channel.VratiVlasnikeModelaAsync(model);
        }
        
        public System.Collections.Generic.List<April2021Client.SR.Vozilo> VratiSvaVozila() {
            return base.Channel.VratiSvaVozila();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<April2021Client.SR.Vozilo>> VratiSvaVozilaAsync() {
            return base.Channel.VratiSvaVozilaAsync();
        }
    }
}
