//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jun2019ClientForm.Evidencija {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RadniDan", Namespace="http://schemas.datacontract.org/2004/07/Jun2019")]
    [System.SerializableAttribute()]
    public partial class RadniDan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Jun2019ClientForm.Evidencija.Log LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Jun2019ClientForm.Evidencija.Log LogoutField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Jun2019ClientForm.Evidencija.Log Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Jun2019ClientForm.Evidencija.Log Logout {
            get {
                return this.LogoutField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoutField, value) != true)) {
                    this.LogoutField = value;
                    this.RaisePropertyChanged("Logout");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Log", Namespace="http://schemas.datacontract.org/2004/07/Jun2019")]
    [System.SerializableAttribute()]
    public partial class Log : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TimeStamp {
            get {
                return this.TimeStampField;
            }
            set {
                if ((this.TimeStampField.Equals(value) != true)) {
                    this.TimeStampField = value;
                    this.RaisePropertyChanged("TimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Evidencija.IEvidencija")]
    public interface IEvidencija {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvidencija/Register", ReplyAction="http://tempuri.org/IEvidencija/RegisterResponse")]
        bool Register(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvidencija/Register", ReplyAction="http://tempuri.org/IEvidencija/RegisterResponse")]
        System.Threading.Tasks.Task<bool> RegisterAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvidencija/Login", ReplyAction="http://tempuri.org/IEvidencija/LoginResponse")]
        bool Login(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvidencija/Login", ReplyAction="http://tempuri.org/IEvidencija/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvidencija/Logout", ReplyAction="http://tempuri.org/IEvidencija/LogoutResponse")]
        bool Logout(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvidencija/Logout", ReplyAction="http://tempuri.org/IEvidencija/LogoutResponse")]
        System.Threading.Tasks.Task<bool> LogoutAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvidencija/GetDates", ReplyAction="http://tempuri.org/IEvidencija/GetDatesResponse")]
        System.Collections.Generic.List<Jun2019ClientForm.Evidencija.RadniDan> GetDates(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvidencija/GetDates", ReplyAction="http://tempuri.org/IEvidencija/GetDatesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Jun2019ClientForm.Evidencija.RadniDan>> GetDatesAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEvidencijaChannel : Jun2019ClientForm.Evidencija.IEvidencija, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EvidencijaClient : System.ServiceModel.ClientBase<Jun2019ClientForm.Evidencija.IEvidencija>, Jun2019ClientForm.Evidencija.IEvidencija {
        
        public EvidencijaClient() {
        }
        
        public EvidencijaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EvidencijaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvidencijaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EvidencijaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Register(string name) {
            return base.Channel.Register(name);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterAsync(string name) {
            return base.Channel.RegisterAsync(name);
        }
        
        public bool Login(string name) {
            return base.Channel.Login(name);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string name) {
            return base.Channel.LoginAsync(name);
        }
        
        public bool Logout(string name) {
            return base.Channel.Logout(name);
        }
        
        public System.Threading.Tasks.Task<bool> LogoutAsync(string name) {
            return base.Channel.LogoutAsync(name);
        }
        
        public System.Collections.Generic.List<Jun2019ClientForm.Evidencija.RadniDan> GetDates(string name) {
            return base.Channel.GetDates(name);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Jun2019ClientForm.Evidencija.RadniDan>> GetDatesAsync(string name) {
            return base.Channel.GetDatesAsync(name);
        }
    }
}
